env: aws

kubernetes:
  config_path: ~/.kube/config
  namespace: test-chaos-ns

aws:
  region: us-east-1
  tag_key: chaosroom
  tag_value: "true"
  states: ["running"]

azure:
  subscription_id: xxx
  resource_group: xxx
